### ISSUE TITLE
adjustments to notification emails

### ISSUE THREAD

**Issue by sigmundch** [kevmoo/github_email_notify#13]
I think it will be useful to:
- add the title of the issue in the subject of the notification email
- add the reporter in the body
- make the title of the issue stand out in the body somehow
- make the body of the issue separate (either by quoting or adding a separator)

For example, here is a before & after example from an issue I just got notified for.

Subject before:

> `dart-lang/sdk#24122` labeled Area-Dart2JS by floitschG

Suggested subject after:

> [+Area-Dart2JS]: dart2js crashes when .packages contains same package name twice (#24122)

Body before:

> User: floitschG - https://github.com/floitschG
> Label: Area-Dart2JS
> 
> [https://github.com/dart-lang/sdk/issues/24122 ](https://github.com/dart-lang/sdk/issues/24122)
>  dart2js crashes when .packages contains same package name twice
> 
> stdout:
> The compiler crashed: FormatException: Same package name occured
> twice. (at offset 56)
>  # 0      parse (package:package_config/packages_file.dart:66:7)
>  # 1      Compiler.setupPackages.<anonymous> (package:compiler/src/apiimpl.dart:403:29)
>  ...

Suggested body after:

> **Issue title**: dart2js crashes when .packages contains same package name twice
>  Reported by [hterkelsen](https://github.com/hterkelsen)
>  Area-Dart2JS added by [floitschG](https://github.com/floitschG)
> ---
> 
>  Original issue contents:
> 
> > stdout:
> > The compiler crashed: FormatException: Same package name occured
> > twice. (at offset 56)
> >  # 0      parse (package:package_config/packages_file.dart:66:7)
> >  # 1      Compiler.setupPackages.<anonymous> (package:compiler/src/apiimpl.dart:403:29)
> >  ...

**Comment by kevmoo** [comment]
![screen shot 2015-08-26 at 11 48 25 am](https://cloud.githubusercontent.com/assets/17034/9502854/7c07b3d0-4be8-11e5-9c65-f96fa83a3a0b.png)

**Comment by sigmundch** [comment]
Thanks Kevin, new emails are awesome! :)
